[package]
name = "russ"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atom_syndication = { version = "0.9.0", default-features = false }
chrono = "0.4.11"
crossterm = "0.17.5"
html2text = "0.1.12"
reqwest = { version = "0.10.6", features = ["blocking"] }
rss = { git = "https://github.com/rust-syndication/rss" }
rusqlite = { version = "0.23.1", features = ["chrono"] }
structopt = "0.3.15"
tui = { version = "0.9.5", default-features = false, features = ["crossterm"] }

[profile.release]
codegen-units = 1
lto = true
