[package]
name = "russ"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
atom_syndication = { version = "0.9", default-features = false }
chrono = "0.4"
copypasta = "0.7"
crossterm = "0.18"
diligent-date-parser = "0.1"
html2text = "0.2"
r2d2 = "0.8"
r2d2_sqlite = "0.17"
rayon = "1.4"
reqwest = { version = "0.10", features = ["blocking"] }
rss = { git = "https://github.com/rust-syndication/rss", rev = "2a975b0" }
rusqlite = { version = "0.24", features = ["chrono"] }
structopt = "0.3"
tui = { git = "https://github.com/fdehau/tui-rs", rev = "25ff2e5", default-features = false, features = ["crossterm"] }

[profile.release]
codegen-units = 1
lto = true
