[package]
name = "russ"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atom_syndication = "0.9.0"
chrono = "0.4.11"
crossterm = "0.17.5"
crossbeam-channel = "0.4.2"
html2text = "0.1.12"
reqwest = "0.10.6"
rss = "1.9.0"
rusqlite = { version = "0.23.1", features = ["chrono"] }
structopt = "0.3.14"
tokio = { version = "0.2.21", default-features = false, features = ["macros"] }
tui = { version = "0.9.5", default-features = false, features = ["crossterm"] }

[profile.release]
codegen-units = 1
lto = true
