[package]
name = "russ"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
crossbeam-channel = "0.4.2"
crossterm = "0.17"
html2text = "0.1.11"
reqwest = { version = "0.10" }
rss = "1.9.0"
structopt = "0.3.14"
rusqlite = { version = "0.23.1", features = ["chrono"] }
tokio = { version = "0.2.21", features = ["full"] }
tui = { version = "0.9.5", default-features = false, features = ['crossterm'] }

[profile.release]
lto = true
