version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:latest

    steps:
      - checkout
      - run:
          name: Install system deps
          command: sudo apt-get update && sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Test
          command: cargo test --all
